import { clerk } from "@clerk/testing/playwright";
import { expect, test as setup } from "@playwright/test";
import { loadE2EEnv } from "./env";
import {
  waitForAuthenticatedRedirect,
  waitForClerkLoaded,
} from "./clerk-helpers";
import path from "path";

/**
 * Authentication setup for Playwright E2E tests
 *
 * Performs ONE login at the start of the test run and saves the authenticated
 * browser state to a file. All subsequent tests reuse this state, eliminating
 * redundant authentication and speeding up test execution.
 *
 * Execution: Runs AFTER global-setup.ts (which generates testing token)
 * Output: e2e/.auth/user.json (saved storage state)
 *
 * Requirements:
 * - CLERK_TEST_USER_EMAIL in environment
 * - CLERK_TEST_USER_PASSWORD in environment
 * - Testing token generated by global-setup.ts
 *
 * @see https://clerk.com/docs/guides/development/testing/playwright/test-authenticated-flows
 */

const authFile = path.join(__dirname, ".auth/user.json");

// Authenticate user and save session state
setup("authenticate", async ({ page }) => {
  console.log("Authenticating test user...");

  // Check for required environment variables
  const env = loadE2EEnv();

  // Navigate to unprotected page that loads Clerk
  await page.goto("/");

  // CRITICAL: Wait for Clerk to fully load before attempting sign-in
  // This eliminates race condition that causes "Password is incorrect" errors
  console.log("Waiting for Clerk to load...");
  await clerk.loaded({ page });
  await waitForClerkLoaded(page, 60000);
  console.log("Clerk loaded, proceeding with sign-in...");

  // Use Clerk's official sign-in helper
  await clerk.signIn({
    page,
    signInParams: {
      strategy: "password",
      identifier: env.CLERK_TEST_USER_EMAIL,
      password: env.CLERK_TEST_USER_PASSWORD,
    },
  });

  console.log("Sign-in successful, verifying authenticated state...");

  // Only verify the authenticated session here.
  // Workspace readiness belongs to the authenticated fixture/tests because
  // /coach is also gated by subscription and Convex bootstrap state.
  await waitForAuthenticatedRedirect(page);
  await expect(page).not.toHaveURL(/\/sign-in(?:\/.*)?(?:\?.*)?$/);
  await expect(page).toHaveURL(/\/coach(?:\?.*)?$/);

  // Save authenticated state for reuse in all tests
  await page.context().storageState({ path: authFile });
  console.log(`Auth state saved to ${authFile}`);
});
